"""students table

Revision ID: a7316cd25694
Revises: 
Create Date: 2020-09-11 15:54:08.515095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7316cd25694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=8), nullable=False),
    sa.Column('course_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code'),
    sa.UniqueConstraint('course_id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('StudentGroups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('Students',
    sa.Column('student_id', sa.String(length=7), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('credit_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('CoursesTaken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=7), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('GroupMembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=7), nullable=True),
    sa.Column('member_role', sa.Enum('member', 'leader', name='roleenum'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['StudentGroups.group_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=False),
    sa.Column('sender_id', sa.String(length=7), nullable=False),
    sa.Column('recipient_id', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student1_id', sa.String(length=7), nullable=True),
    sa.Column('student2_id', sa.String(length=7), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student1_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['student2_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('student1_id'),
    sa.UniqueConstraint('student2_id')
    )
    op.create_table('WaitLists',
    sa.Column('waitlist_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.PrimaryKeyConstraint('waitlist_id'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('waitlist_id')
    )
    op.create_table('Posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.Column('waitlist_id', sa.Integer(), nullable=True),
    sa.Column('poster_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['waitlist_id'], ['WaitLists.waitlist_id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_id'),
    sa.UniqueConstraint('poster_id'),
    sa.UniqueConstraint('waitlist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posts')
    op.drop_table('WaitLists')
    op.drop_table('Reviews')
    op.drop_table('Messages')
    op.drop_table('GroupMembers')
    op.drop_table('CoursesTaken')
    op.drop_table('Students')
    op.drop_table('StudentGroups')
    op.drop_table('Courses')
    # ### end Alembic commands ###
